### ISSUE TITLE
How can I use EYE to reify/dereify a formula.

### ISSUE THREAD

**Issue by blackwint3r** [eyereasoner/eye#26]
In CWM I can use —reify and —dereify options , to replace the statements in the store with statements describing them, and undo the effects.
Newly to EYE, after some search still don’t know how can I achieve this. 

And I also wonder if reify and dereify could be implement as a built-in function, which in my opinion will be very convenient and useful.

**Comment by josd** [comment]
Thanks for asking and I have added an example at https://github.com/josd/eye/tree/master/reasoning/reif

We use the generic [e:becomes](http://eulersharp.sourceforge.net/2003/03swap/log-rules.html#becomes) built-in. You can also see how it is used in [gps](https://github.com/josd/eye/tree/master/reasoning/gps) esp. in conjunction with [e:finalize](http://eulersharp.sourceforge.net/2003/03swap/log-rules.html#finalize).
We also use a rule of the form `true <= {goal}.` which is an immediate goal that is executed when the n3 file is loaded.

While testing the example I also found a bug which is now fixed in https://github.com/josd/eye/releases/tag/v21.1218.1852

**Comment by blackwint3r** [comment]
Thank you for your work and explanation,  your test file is very helpful. 

But use e:become I think I can only reify statements,  not rules (with variable) or graphs or formula. (or maybe there is a way to do this?). See example here: https://www.w3.org/DesignIssues/Reify.html

And ask out of curiosity, I found e:become is really power,  does it break the monotonicity of n3 logic?   (for your can delete triples used as premises, make the previous conclusion not correct any more)

**Comment by josd** [comment]
The built-in `e:becomes` indeed works with "ephimeral" triples which is how we implement linear implication.
It might be a good idea to explicitly declare ephimeral predicates e.g. like in prolog `:- dynamic(p/2).`

Contrary to what one might think, [linear logic is monotone](https://cstheory.stackexchange.com/questions/27224/categorical-semantics-for-non-monotonic-logics).
