### ISSUE TITLE
math:sum fail to resolve... sometimes

### ISSUE THREAD

**Issue by pchampin** [eyereasoner/eye#5]
Running the following in the latest version of EYE
```
{ (20 20) math:sum ?x. (?x 2) math:sum ?y. } => { :ANSWER1 :IS ?y }.
{ (?x 2) math:sum ?y. (20 20) math:sum ?x. } => { :ANSWER2 :IS ?y }.
{ (20 20) math:sum ?x. (?x ?y) math:sum 42. } => { :ANSWER3 :IS ?y }.
{ (?x ?y) math:sum 42. (20 20) math:sum ?x. } => { :ANSWER4 :IS ?y }.
{ (20 20) math:sum ?x. (1 1) math:sum ?y. (?x ?y) math:sum ?z. } => { :ANSWER5 :IS ?z }.
{ (20 20) math:sum ?x. (?x ?y) math:sum ?z. (1 1) math:sum ?y. } => { :ANSWER6 :IS ?z }.
{ (?x ?y) math:sum ?z. (20 20) math:sum ?x. (1 1) math:sum ?y. } => { :ANSWER7 :IS ?z }.
```
I get all answers but ANSWER4... strange

**Comment by josd** [comment]
Thanks for your observation @pchampin and the latest EYE now gives `:ANSWER4 :IS 2 .`

**Comment by josd** [comment]
@pchampin your 7 tests are now included in https://josd.github.io/eye/reasoning/bi/math_flowc.n3
and there was still an issue with and extra test
`{ (?x ?y) math:sum ?z. (20 20) math:sum ?z. (1 1) math:sum ?y. } => { :ANSWER8 :IS ?x }.`
which is now fixed in the latest EYE
See also the results with CWM and EYE in https://gist.github.com/josd/76ee216dbcd1a5cfff7eb50bc6ad4305

**Comment by josd** [comment]
What is not working is
```
{(?X ?Y) math:sum 8. (?X ?Y) math:difference 2} => {:ANSWER8 :IS (?X ?Y)}.
{(?X ?X) math:sum 2} => {:ANSWER9 :IS ?X}.
{((5 ?X ?X)!math:product (-2 ?X)!math:product 6) math:sum 9} => {:ANSWER10 :IS ?X}.
```

**Comment by josd** [comment]
v20.1020.2137: reverting to the original flow patterns for math:sum, math:product, math:difference and math:quotient
